[tool.poetry]
name = "poetry-nebular"
version = "0.1.0"
description = "ai assistants playground"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12, <3.13"
pyautogen = "^0.2.35"
azure-identity = "^1.17.1"
gradio = "^4.42.0"
fastapi = "^0.112.1"
uvicorn = "^0.30.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
