code_generation_task:
  description: >
    根据以下信息生成代码, 如果是前端代码，所有div必须包含唯一的语义化或者uuid的id属性：
    1. 文件路径：{file_path}
    2. 文件类型：{file_type}
    3. 需求描述：{requirement}
    4. 项目信息：
        - 类型：{project_type}
        - 描述：{project_description}
        - 框架：{frameworks}
    5. 相关文件：{resources}
    6. 引用关系：{references}
  expected_output: >
    @file: {file_path}
    @description: [简要描述文件的主要功能和用途]
    @tags: [相关标签，如framework_xxx,feature_xxx等，用逗号分隔]
    @version: 1.0.0
    @version_id: [UUID格式的版本ID]
    ---
    [完整的代码实现，包含：
    1. 必要的导入语句
    2. 类型定义（如果需要）
    3. 主要功能实现
    4. 错误处理
    5. 导出语句（如果需要）]
  agent: code_generator

chat_task:
  description: >
    根据以下对话信息生成回复：
    1. 内容：{text}
    要求：
    1. 保持友好和专业的语气
    2. 根据对话类型和标签调整回复风格
    3. 如果是普通对话，给出合适的回应
    4. 如果提到了其他Staff，注意回复的针对性
    5. 避免过于冗长的回复
    6. 保持对话的连贯性
  expected_output: >
    [回复内容]
  agent: code_generator

