intent_analysis_task:
  description: >
    分析以下对话的意图，判断是否是有意义的对话：

    对话信息：
    1. 内容：{text}
    2. 类型：{type}
    3. 是否为旁白：{is_narratage}
    4. 是否为悄悄话：{is_whisper}
    5. 标签：{tags}
    6. 是否提及其他Staff：{mentioned_staff_bools}

    要求如下：
    1. 首先判断对话是否有实质内容：
        - 是否包含明确的意图或目的
        - 是否需要响应或处理
        - 是否包含实质性的内容
        - 如果是纯粹的表情、语气词或无意义的重复，返回"general chat"

    2. 如果对话有意义：
        - 用一句简洁的话描述意图
        - 包含关键动作和目标
        - 如果是工具调用，说明调用的工具
        - 如果是任务相关，说明任务类型

    3. 如果是代码生成请求：
        - 说明需要生成的代码类型（如Python, HTML, CSS等）
        - 描述代码的用途和功能
        - 列出关键需求和约束
        - 标注是否需要特定的框架或库
        - 识别需要生成的所有文件
        - 确定每个文件的类型和用途
        - 识别文件之间的关联（如HTML引用CSS和JS）
        - 确定项目的整体结构
        - is_code_request字段返回true
    4. 如果是已经生成了代码：
        - 比如parameters的text字段中已经生成了代码或者其他资源，则is_code_request字段返回false
        - 根据生成的代码中parameters的text字段中的头部信息获取file_path和mime_type用于返回的code_details.resources里。
  expected_output: |
    返回格式为JSON对象，示例如下：
    {{
        "intent": "意图描述，无意义对话则返回'general chat'",
        "reason": "说明意图分析的原因",
        "is_code_request": true/false,
        "code_details": {{
            "project_type": "web/python/java等项目类型",
            "project_description": "项目整体描述",
            "resources": [
                {{
                    "file_path": "/src/html/index.html",
                    "type": "html",
                    "mime_type": "text/html",
                    "description": "主页面文件",
                    "references": ["style.css", "main.js"]
                }},
                {{
                    "file_path": "/src/css/style.css",
                    "type": "css",
                    "mime_type": "text/css",
                    "description": "样式文件"
                }},
                {{
                    "file_path": "/src/js/main.js",
                    "type": "javascript",
                    "mime_type": "text/javascript",
                    "description": "交互脚本"
                }}
            ],
            "requirements": ["需求1", "需求2"],
            "frameworks": ["react", "vue", "@popperjs/core", "normalize.css"]
        }}
    }}
  agent: intent_analyzer

