task_decomposition_task:
  description: |
    请你首先理解并且分析整体资源的架构和作用，其次将迭代需求:{iteration_requirement}, 分解为针对每个resource文件的修改任务。涉及到的资源在{resource_list}中（每个资源包含file_path和resource_id）。要求：
    1. 每个任务对应一个文件的修改
    2. 明确修改类型（create/update/delete）
    3. 标注修改位置（行号或代码块标识）
    4. 保持文件完整性（返回完整文件内容）

  expected_output: |
    {{
        "intent": "resource_iteration", 
        "reason": "基于迭代需求的资源修改任务",
        "is_code_request": true/false,
        "code_details": {{
            "project_type": "迭代项目",
            "project_description": "基于迭代需求对多个资源进行修改",
            "resources": [
                {{
                    "file_path": "文件路径（如/src/html/index.html）",
                    "type": "根据文件扩展名确定类型如html",
                    "mime_type": "根据文件类型确定（如text/html）",
                    "description": "针对任务需求，要对这个资源进行怎样的操作和改动的描述",
                    "action": "create|update|delete",
                    "resource_id": "资源ID",
                    "position": "如果是修改，指出有问题的修改位置。如果是新增或者删除则为全部"
                }},
                // ... 其他资源
            ],
            "requirements": ["从迭代需求中提取的核心要求1", "核心要求2"],
            "frameworks": ["涉及到的框架"]
        }}
    }}
  agent: task_decomposer
